#!/usr/bin/env bash

# Author: Cade M. Teets
# UWNetID: cteets
# CSE 374 25su Homework 2
# Date: [07/09/2025]

# Description: [Script that combines the text content of files passed as arguments to an outFile]
arg1=$2
#check if the number of args is less than 2. If so, exit with error code and output to stderr
if [ $# -lt 2 ]; then
    echo "Usage: ./combine outputfilename [inputfilename ...]" 1>&2
    exit 1
fi

#check if the file name passed in the arguements already exits. If so, exit with error code and output to stderr
if [ -e "$1" ]; then
    echo "Error: Output file should not exist" 1>&2
    exit 1
fi

# set a variable for the outFile name and the count
outFile=$1
count=0

# shift so that the next inputFile is stored in $1
shift

# set variable numArgs equal to the number of remaing args
numArgs=$#

# While loop is concatenate the files to the first file arg
# check for count < numArgs
# cat fileArg to outFile and then shift over 
while [ $count -lt $numArgs ]; do
    # if there are any files passed that do not exist, redirect stderr to outFile  
    # then shift and check again, otherwise exit the loop  
    while [ ! -e "$1" ]; do
        cat "$1" 2>> $outFile
        shift
        ((count++))
    done
    
    # Add the output of arg1 to outFile
    cat "$1" >> $outFile
    

    # increase the counter and shift the args over so the new file can be concatenated.
    ((count++))
    shift
done

#exit with no error
exit 0
